version: "3.7"
services:
  app:
    image: {{ cookiecutter.org_name }}/{{ cookiecutter.project_name }}:{{ cookiecutter.deploy_image_version }}
    container_name: {{ cookiecutter.project_name }}
    restart: unless-stopped
    shm_size: '2gb'
    env_file:
      - .env
